services:
  favoriterates.migrationsservice:
    image: favoriterates.migrationsservice
    build:
      context: .
      dockerfile: src/MigrationsService/FavoriteRates.MigrationsService/Dockerfile
    environment:
      - ConnectionStrings__UsersServiceConnection=Host=favoriterates.pg;Database=usersdb;Username=postgres;Password=postgres;
      - ConnectionStrings__FinanceServiceConnection=Host=favoriterates.pg;Database=financedb;Username=postgres;Password=postgres;
    depends_on:
      - favoriterates.pg

  favoriterates.usersservice:
    image: favoriterates.usersservice:latest
    build:
      context: .
      dockerfile: src/UsersService/FavoriteRates.UsersService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=favoriterates.pg;Database=usersdb;Username=postgres;Password=postgres;
      - Jwt__Secret=Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Jwt__ExpirationInMinutes=10
      - Jwt__Issuer=favoriterates.usersservice
      - Jwt__Audience=favoriterates.financeservice
    depends_on:
      favoriterates.migrationsservice: 
        condition: service_completed_successfully
        
  favoriterates.financeservice:
    image: favoriterates.financeservice:latest
    build:
      context: .
      dockerfile: src/FinanceService/FavoriteRates.FinanceService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=favoriterates.pg;Database=financedb;Username=postgres;Password=postgres;
      - Jwt__Secret=Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      - Jwt__Issuer=favoriterates.usersservice
      - Jwt__Audience=favoriterates.financeservice
      - UpdateCurrencies__UpdateAt=16:30:00
      - UpdateCurrencies__UpdateIfEmpty=true
      - UpdateCurrencies__ClientBaseUrl=https://www.cbr.ru
      - UpdateCurrencies__ClientPath=/scripts/XML_daily.asp
      - UpdateCurrencies__ClientMaxRetryAttempts=3
      - UpdateCurrencies__ClientRetryDelayInSeconds=2
    depends_on:
      favoriterates.migrationsservice:
        condition: service_completed_successfully
        
  favoriterates.apigateway:
    image: favoriterates.apigateway:latest
    build:
      context: .
      dockerfile: src/ApiGateway/FavoriteRates.ApiGateway/Dockerfile
    ports:
      - "5147:8080"
    environment:
      - ReverseProxy__Clusters__users-cluster__Destinations__destination1__Address=http://favoriterates.usersservice:8080
      - ReverseProxy__Clusters__finance-cluster__Destinations__destination1__Address=http://favoriterates.financeservice:8080
    depends_on:
      - favoriterates.usersservice
      - favoriterates.financeservice
      
  favoriterates.pg:
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - favoriterates.pgvolume:/var/lib/postgresql
        
volumes:
  favoriterates.pgvolume: