<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\FavoriteRates.SharedLibrary\FavoriteRates.SharedLibrary.csproj" />
      <ProjectReference Include="..\FavoriteRates.FinanceService.Domain\FavoriteRates.FinanceService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Scrutor" Version="6.1.0" />
    </ItemGroup>

</Project>
